### ISSUE TITLE
EMS being able to drag people

### ISSUE THREAD

**Issue by Hmestrovicg** [InZidiuZ/LegacyRP-feedback#83] opened 2019-03-26 21:45 UTC
**Suggester:** 
Clancy_McLroy#4739
 
**Summary:**
EMS should be able to drag people like PD can. (I Know this was proposed in the past, but it was poorly explained and presented)
 
**Reason:**
Many a time people tend to pass out in the middle of busy streets where the ongoing traffic is simply dangerous to RP a proper scenario of helping people, by dragging people we could get them to safety. Also when person passes out in his vehicle we could get him out and try to revive him.
 
**Economy:**
Only economy that will be affected is EMS getting paid more by getting more cases to revive people, and people in more cases get to keep their stuff (by not dying). People keeping more stuff could be solved by implementing that person loses a certain amount of stuff he is carrying when revived (RP explanation 1: "Somebody used the opportunity and robbed you while you were knocked out" ; RP explanation 2: "You dropped some of your items while knocked-out and they got lost")

**Comment by N8teZero** [comment] 2019-04-25 23:50
Duplicate of #129

**Closed by N8teZero** 2019-04-25 23:50 UTC
Labels: feature request
