### ISSUE TITLE
Eject player out of vehicle, respawn player when dead to dead revivable position.

### ISSUE THREAD

**Issue by OriginFacts** [InZidiuZ/LegacyRP-feedback#87] opened 2019-03-27 08:39 UTC
**Suggester:**
E-410 D. Ortiz (Facts)

 
**Summary:**
Eject player who is stuck in vehicle to an open position. Reset player when in dead animation to a new player so he doesn't disappear or phase from existance.
 
**Reason:**
If a player dies in a vehicle, he does not need to respawn and lose all things or wait for an admin to help him and the medic responding.
 
**Economy:**
Admins are less needed to treat this bug and medics can perform their jobs.

**Comment by N8teZero** [comment] 2019-04-25 23:50
Duplicate of #129

**Closed by N8teZero** 2019-04-25 23:50 UTC
Labels: feature request
