### ISSUE TITLE
EMS suggestions to make EMS more efficient and non-dependant on PD when the situation isnt dangerous .

### ISSUE THREAD

**Issue by Boblishky** [InZidiuZ/LegacyRP-feedback#76] opened 2019-03-21 21:01 UTC
Suggester: Boblishky#6918 EMS rank Specialist 

Summary:I would like the EMS to be able to drag people or receive a call where it says that the person is dead in a car or a difficult to get to place .When im on duty as a EMS 70 percentage of calls i either rely on PD or cont see the person(BUGGED)/ or cont get the person out of the car . This means that i need to distract the PD and anger the civilian which cont get help because i have many calls (because im the only EMS on  the server.)

Reason:So that the EMS can be way more quick and efficient because mostly there is only one EMS on the server . 

Economy: This can make EMS earn more money but the salary is broken anyways so it wont change anything because they do the most work so they should get more money .

**Comment by N8teZero** [comment] 2019-04-25 23:49
Duplicate of #129

**Closed by N8teZero** 2019-04-25 23:49 UTC
Labels: feature request
